SELECT DISTINCT a1.AIRPORT, a2.AIRPORT, f1.DISTANCE
FROM flights f1, airports a1, airports a2, flights f2
WHERE f1.DISTANCE >= 4000 AND f1.ORIGIN_AIRPORT_ID = a1.ID AND
f1.DESTINATION_AIRPORT_ID = a2.ID AND
f1.ID = f2.ID AND f1.ORIGIN_AIRPORT_ID < f2.DESTINATION_AIRPORT_ID