SELECT DISTINCT f1.ORIGIN_AIRPORT_ID, f1.DESTINATION_AIRPORT_ID, avg(f1.DISTANCE) AS media
FROM flights f1, flights f2
WHERE f1.ID = f2.ID AND
f1.ORIGIN_AIRPORT_ID < f2.DESTINATION_AIRPORT_ID
GROUP BY f1.ORIGIN_AIRPORT_ID, f1.DESTINATION_AIRPORT_ID